# Generated by Django 3.0.3 on 2021-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Admin_Details',
            },
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default=None, max_length=100)),
                ('LastName', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Password', models.CharField(default=None, max_length=100)),
                ('mobile', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('City', models.CharField(default=None, max_length=100)),
                ('State', models.CharField(default=None, max_length=100)),
                ('Status', models.CharField(default=None, max_length=100)),
                ('AbusingCounter', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'User_details',
            },
        ),
    ]
