# Generated by Django 3.0.3 on 2021-01-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseID', models.CharField(default=None, max_length=100)),
                ('OfficerID', models.CharField(default=None, max_length=100)),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Note', models.CharField(default=None, max_length=100)),
                ('Result', models.CharField(default=None, max_length=100)),
                ('Status', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Case_details',
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseID', models.CharField(default=None, max_length=100)),
                ('History', models.CharField(default=None, max_length=300)),
                ('Date', models.DateField()),
                ('OfficerID', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'CaseHistory',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseID', models.CharField(default=None, max_length=100)),
                ('EvidenceId', models.CharField(default=None, max_length=100)),
                ('Type', models.CharField(default=None, max_length=100)),
                ('Suspects', models.CharField(default=None, max_length=100)),
                ('Image', models.ImageField(upload_to='img/images')),
                ('Note', models.CharField(default=None, max_length=100)),
                ('Rank', models.CharField(default=None, max_length=100)),
                ('Date', models.DateField()),
                ('OfficerID', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Evidence',
            },
        ),
        migrations.CreateModel(
            name='Officer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default=None, max_length=100)),
                ('LastName', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
                ('mobile', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('City', models.CharField(default=None, max_length=100)),
                ('State', models.CharField(default=None, max_length=100)),
                ('Image', models.ImageField(upload_to='img/images')),
            ],
            options={
                'db_table': 'Officer_details',
            },
        ),
        migrations.CreateModel(
            name='Suspects_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseID', models.CharField(default=None, max_length=100)),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
                ('mobile', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Relation', models.CharField(default=None, max_length=100)),
                ('Date', models.DateField()),
                ('Rank', models.CharField(default=None, max_length=100)),
                ('Image', models.ImageField(upload_to='img/images')),
                ('Note', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Suspects_details',
            },
        ),
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
