# Generated by Django 3.0.3 on 2021-01-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0003_remove_suspects_details_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspects_details',
            name='Username',
        ),
    ]
