# Generated by Django 3.0.3 on 2021-01-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0004_remove_suspects_details_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='EvidenceId',
            new_name='Evidence',
        ),
    ]
