# Generated by Django 3.0.3 on 2021-01-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0005_auto_20210122_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evidence',
            new_name='Evidence_Details',
        ),
        migrations.AlterModelTable(
            name='evidence_details',
            table='Evidence_Details',
        ),
    ]
