# Generated by Django 3.0.3 on 2021-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0006_auto_20210122_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspects_details',
            name='OfficerID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
