# Generated by Django 3.0.3 on 2021-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0007_suspects_details_officerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_details',
            name='CaseType',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
