# Generated by Django 3.0.3 on 2021-01-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0008_case_details_casetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_details',
            name='GuiltyID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
