# Generated by Django 3.0.3 on 2021-01-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCriminal', '0009_case_details_guiltyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_details',
            old_name='Result',
            new_name='GuiltyRelation',
        ),
    ]
